name: TestPlugin
main: furiocelot\testplugin\TestPlugin
version: 0.1.0
api: [3.0.0, 4.0.0]

load: POSTWORLD
author: FuriOcelot
description: 플러그인 테스트용 플러그인입니다!
website: https://github.com/FuriOcelot/TestPlugin